steps:
  # 1. Install Poetry and dependencies (no requirements.txt needed)
  - name: 'python:3.11.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Poetry
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        poetry config virtualenvs.in-project true
        poetry install --sync --no-interaction --no-ansi --with dev

  # 2. Run tests
  - name: 'python:3.11.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PATH="$HOME/.local/bin:$PATH"
        poetry run pre-commit run --all-files
        poetry run pytest -q

  # 3. Deploy on success
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy flaccid-job \
          --source . \
          --region us-central1 \
          --service-account flaccid-runtime-sa@${PROJECT_ID}.iam.gserviceaccount.com \
          --quiet

timeout: '1200s'
