[tool.poetry]
name = "flaccid"
version = "0.1.0"
description = "Modular FLAC CLI Toolkit"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.3"
pydantic = "^2.6"
dynaconf = "^3.2"
aiohttp = "^3.9"
keyring = "^25.2"
mutagen = "^1.47"
rich = "^13.6"
sqlalchemy = "^2.0"
watchdog = "^4.0"
python-dotenv = "^1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
pytest-asyncio = "^0.21"

[tool.poetry.scripts]
fla = "flaccid.__main__:app"
flaccid = "flaccid.__main__:app"

[[tool.poetry.packages]]
include = "flaccid"
from = "src"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
