[tool.poetry]
name = "flaccid"
version = "0.1.0"
description = ""
authors = ["georges <geoooorges@icloud.com>"]
readme = "README.md"
packages = [
  { include = "flaccid", from = "src" }
]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
typer = "^0.12.3"
google-cloud-storage = "2.14.0"
gcsfs = "2023.10.0"
pandas = "2.1.4"
pyarrow = "14.0.2"
typing-extensions = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
black = "^25.1.0"
flake8 = "^7.3.0"
pre-commit = "^3.7.0"

[tool.poetry.scripts]
flaccid = "flaccid.__main__:app"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["src/tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
asyncio_default_fixture_loop_scope = "function"