name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python & Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry config virtualenvs.in-project true
          poetry install --sync --no-interaction --no-ansi
      - name: Build distributions
        run: |
          poetry build
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --no-interaction --username __token__ --password "$POETRY_PYPI_TOKEN"

